# Generated by Django 2.2.12 on 2020-05-25 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Regist',
            fields=[
                ('id_regist', models.AutoField(primary_key=True, serialize=False)),
                ('occupation_value', models.IntegerField()),
                ('timestamp', models.TimeField(auto_now=True)),
                ('trash_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_trash_app.Bin')),
            ],
        ),
    ]
