# Generated by Django 2.2.12 on 2020-05-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_trash_app', '0002_auto_20200525_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regist',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
